name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v2

      # Install Node 14
      - name: Setup Node
        uses: actions/setup-node@1
        with:
          node-version: 14

      # Install dependencies
      - run: npm ci

      # Build and Deploy
      - run: npm run build
      - run: echo "🎉"

      # - run: git subtree push --prefix dist origin gh-pages
